# Generated by Django 4.1.3 on 2022-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last_name"),
                ),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Movie_name")),
                ("genre", models.CharField(max_length=50, verbose_name="Movie_name")),
                ("year", models.DateField()),
                ("actor", models.ManyToManyField(to="djangoapp.actor")),
            ],
        ),
    ]
