# Generated by Django 4.1.3 on 2022-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoapp",
            "0002_remove_movie_actor_actor_movies_alter_actor_gender_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="actor", name="movies",),
        migrations.AddField(
            model_name="movie",
            name="actor",
            field=models.ManyToManyField(to="djangoapp.actor"),
        ),
    ]
